### ISSUE TITLE
Migrate away from Yarn

### ISSUE THREAD

**Issue by cseitz** [hacksu/hacksu-website#37]
Yarn v1 is no longer maintained and I do not recommend we use it at all.

For a suitable and very-well-featured alternative, I recommend https://pnpm.io/

PNPM is a very efficient pkg manager that I've been using for quite some time.

## Tasks

- [ ] Update docs to include usage of `pnpm`
- [ ] Remove `yarn.lock`
- [ ] Run `pnpm install`
- [ ] Commit pnpm lockfile

**Comment by Struck713** [comment]
I've been using [Bun](https://bun.sh) for quite some time now, it seems to be the fastest on the market by a long shot. Maybe we consider moving to it instead?
